version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0  # Use Redis URL for your application
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: